---
title: "徐医生的博客"
languageCode: "zh-CN"
baseURL: "http://eason-xu.github.io"
copyright: "Copyright (c) 2015. All rights reserved."
MetaDataFormat: "yaml"
canonifyurls: true
builddrafts: false
PaginatePath: paginator
pygmentsStyle: "default"
pygmentsUseClasses: true
disablePathToLower: true 
hasCJKLanguage: true
Taxonomies:
  tag: "tags"
  category: "categories"
params:
  GitHubUser: "eason-xu"
...